# Welcome to the First Notebook for the Mini Project

# The Print Function

#### To start off with we will first see how we can see the contents which are stored in a variable

Let us define a variable 'players' which stores the number of players that are present in a game.

In [0]:
players = 10

The contents of the variable 'players' can be shown by using the print function

In Python the print function has the syntax as shown:

In [2]:
print(players)

10


As you can see this gives the output of 10 which is what we had stored in the varible 'players

# Conditional- Statements

# If-Else conditionals

Let us first define a few variables

In [0]:
a = 10
b = 5
c = 15

The following code will show you how to use an if-else conditional

In the following code we will be using the if-else to see which is the biggest number out of a, b and c

Surely this isn't the most efficient way of doing this problem but the idea is to demonstrate the use of the if-else conditional

In [4]:
if a<b :                             # Don't forget the ':' here
    if b<c:
        print('c is the largest')
    elif b>c:                        # elif is the syntax for "Else-if" in python
        print('b is the largest')
    else:
        print('b and c are equal and they are the largest')

elif a>b:
    if a<c:
        print('c is the largest')
    elif a>c:                        
        print('a is the largest')
    else:
        print('a and c are equal and they are the largest')

elif a==b:                   # In python we use a single'=' for assigning a number and '==' for making a comparison
    if a<c:
        print('c is the largest')
    elif a>c:                        
        print('a and b are the largest')
    else:
        print('a, b and c are equal')

c is the largest


#### One thing that is worth noticing is that in python indentation matters

If we don't do that then Python will be very confused as to which elif/else falls under which if

# Looping Statements

# For-Loops

For loops are used to help us go through all the elements of a list, tuple, dictionary or other data structures

If you don't understand any of those last few terms don't worry about it, we'll explain it to you a later on in this tutorial

The following example will help you understand how a for loop works and how it makes code simpler

In [0]:
#Let us start by initialising a list
#Again if you don't know what a list is don't worry about it we will explain it to you soon enough

digits = [1,2,3,4,5,6,7,8,9,0]

If we want to print all the elements of the digits list then we can either do it manually or we can use a for loop

In [6]:
# Method 1 - Doing it Manually
print(digits[0])
print(digits[1])
print(digits[2])
print(digits[3])
print(digits[4])
print(digits[5])
print(digits[6])
print(digits[7])
print(digits[8])
print(digits[9])

1
2
3
4
5
6
7
8
9
0


In [7]:
# Method 2 - Doing it with a for loop

for i in range(0, 10, 1): # We can give a range over which i iterates using the "range" function 
    print(digits[i])      # The range function has the parameters (initial value, final value + 1, step value)
                          # Notice how the second arguement says final_value + 1, this means that for this example
                          # i will not take the value 10 but will go only up to 9

1
2
3
4
5
6
7
8
9
0


So you can now see how having a for-loop makes writing code much shorter

# Lists

List - a list is a collection of variables of different types and can be updated when needed

In [0]:
#initialising a list with no values
list1 = []

### Initialising a list with some values

In [9]:
list2 = [1,"a",True]
#note that you can have elements of all data types in a list
print(list2)

[1, 'a', True]


The elements of a list can also be lists, In that case the list will be multi dimensional

In [10]:
list4 = [[1,2,3],[4,5,6],[7,8,9]]
print(list4)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [0]:
#accessing the elements of a list

#indexing also starts from -1 from the end of the list, below is an explanation of the two systems of indexing

#       element1 element2 element3 element4 element5
       
#index:   0         1        2        3        4

#index:  -5        -4       -3       -2       -1

#both these systems of indexing is accepted

In [12]:
list3 = [1,2,3,4,5,6,7,8,9]
#suppose you want the 5th element of the list
a = list3[4]
print("The fifth element is "+str(a))

The fifth element is 5


In [13]:
#Suppose you want to acess the 2nd last element
b = list3[-2]
print("The second last element is "+str(b))

The second last element is 8


In [14]:
#suppose you want to access elements 2nd to 5th position
c = list3[1:5]     #note that the element at index 5 is not printed
print("Elements 2 to 5 are",c)

Elements 2 to 5 are [2, 3, 4, 5]


In [15]:
#Suppose you want all the elements after the third
d = list3[2:]      #note that the third element or the element at index 2 is included
print("Third element onwards",d)

Third element onwards [3, 4, 5, 6, 7, 8, 9]


In [16]:
#Suppose you want all the elements till the 6th element
e = list3[:6]      #note that the element at index 6 or the 7th element is excluded
print("Upto the 6th element",e)

Upto the 6th element [1, 2, 3, 4, 5, 6]


In [17]:
#suppose you want all the elements till the second last element
f =list3[:-1]
print("Upto the second last element",f)

Upto the second last element [1, 2, 3, 4, 5, 6, 7, 8]


### Updating a list

In [18]:
#Suppose you want to add the element 10 at the end of list3
list3.append(10)
print("After appending 10",list3)

After appending 10 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [19]:
#suppose you want to insert the element at the index 4
list3.insert(4,11)
print("After inserting 11",list3)

After inserting 11 [1, 2, 3, 4, 11, 5, 6, 7, 8, 9, 10]


In [20]:
#Suppose you want to delete an element of the list and you know the value
list3.remove(10) #this will remove the first occurence of 10 in list3
print("After removing 10",list3)

After removing 10 [1, 2, 3, 4, 11, 5, 6, 7, 8, 9]


In [21]:
#Suppose you want to delete an element of a list by index
del list3[2]
print("After deleting the element at index 2",list3)

After deleting the element at index 2 [1, 2, 4, 11, 5, 6, 7, 8, 9]


### Length of a list

In [22]:
length = len(list3)
print("Length of list3 is",length)

Length of list3 is 9


### numpy - it is a library used for performing Linear Algebra

In [0]:
import numpy as np
list3 = np.array(list3) #list3 is now a numpy array

In [24]:
#suppose you want to reshape list3 to 3x3 (there are 12 elements now)
list3 = list3.reshape((3,3))
print("Reshaped list3:")
print(list3)

Reshaped list3:
[[ 1  2  4]
 [11  5  6]
 [ 7  8  9]]


In [25]:
#Suppose you want to know the shape of a list
shape = list3.shape
print("Shape of list3 is",shape)

Shape of list3 is (3, 3)


In [26]:
#Suppose you want all the unique values in a list
list5 = [1,2,2,4,4,7,8,9,4,6,6]
list5 = np.array(list5)
uq = np.unique(list5)
print("The unique values in list5 are",uq)

The unique values in list5 are [1 2 4 6 7 8 9]


# Dictionary

dictionary is a datatype storing key value pairs. Where in lists each element is represented by its index, in a dictionary each element is represented by its key

In [0]:
dict1 = {'a':'apple','b':'ball','c':'cat'}
dict2 = {1:'apple',2:'ball',3:'cat'}
#As you see the keys in dict 1 are 'a','b','c' and in dict2 are 1,2,3

### Accessing elements

In [28]:
#Suppoose youu want the element correspoding to key 1
a = dict2[1]
print("Element of key 1 is "+a)

Element of key 1 is apple


In [29]:
#Adding a new key value pair
dict2[4] = 'dog'
print("After adding new pair",dict2)

After adding new pair {1: 'apple', 2: 'ball', 3: 'cat', 4: 'dog'}


In [30]:
#Getting all the values in a dictionary
val = dict2.values()
print("Values in dict2",val)

Values in dict2 dict_values(['apple', 'ball', 'cat', 'dog'])


### Change a value in a dict

In [31]:
dict2[2] = 'play'
print("Dict2 after changing")
print(dict2)

Dict2 after changing
{1: 'apple', 2: 'play', 3: 'cat', 4: 'dog'}


# Functions

Functions are small segments of code that are written once and can be used multiple times instead of writing the code again and again

In [0]:
#How to define a func
def func_name(parameters):
  '''
  your function body
  '''

func_name is your choice of function name and in the paranthesis you can keep all the variables the function accepts

In [0]:
#A simple function that takes two parameters and returns their sum
def sum(a,b):
  tot = a+b
  return tot

In [34]:
i = 10
j = 23
total = sum(i,j)
print("Output is",total)

Output is 33


# Classes

Let's look at classes in python

Classes are used in across Object Oriented Programming, to combine data and functionality together into a single bundle. 

Creating a class, creates a new type of object, which can have multiple instances

These instances of classes are called objects

#### Defining a Class

#Defining a class with name as ClassName

class ClassName:
    
    #Statements within classes

#### Contents within a class : 
Data as well as functions...
These are known as attributes of the class

In [0]:
class ClassName:
    
    #Some data 

    number=5
    
    #Some functions
    
    def result():
        return number

#### Initialising a Class

Initialising a class refers to creating an instance of the class. To initialise an instance of the class, the syntax used is:

In [0]:
p=ClassName()  #This creates an object (instance of the class) p of the class ClassName, as defined in the previous

#### The first parameter of any function in class  (self)

The first parameter in all functions of the class refer to the current instance of the class, and is used to refer to the variables of the class. This parameter is generally named as self, but it need not be so always.

In [0]:
class ClassName:
    
    
    def function(self,x,y):
        return 

#### The __init__() function

The _init_() function is a built-in function in all the classes. It is the first function to be executed each time a class is initialised. It is mainly used to assign values to the object properties


In [0]:
class ClassName:
    
    def __init__(self,value1,value2):
        
        #We use self to access the variables belonging to the class
        self.property1= value1           # The data attribute "property1" of the class is assigned as value1
        self.property2= value2           # The data attribute "property2" of the class is assigned as value2
        
        
#While initialising an instance of the class:

p=ClassName(5,10)           
#We pass the parameters as 5 and 10 which as stored as property1 and property2 of the class instance

#### Defining some other functions in the class

Other functions can be defined in the class as well, apart from the _init_() function, but remember that the first parameter refers to the instance of the class, used to refer its variables (generally self)

In [0]:
class ClassName:
    
     def __init__(self,value1,value2):
        
        #We use self to access the variables belonging to the class
        self.property1= value1           # The data attribute "property1" of the class is assigned as value1
        self.property2= value2           # The data attribute "property2" of the class is assigned as value2
   
     def funct1(self,a,b):
        
        #The same rule applies, self is used to access the variables belonging to the class
        #Other syntax remains same as ordinary functions
        
        sum_property1_a_b= self.property1 + a + b
        print("Operation Complete")
        
        return sum_property1_a_b

#### Calling the attributes of the class from outside : Functions and Data Variables

In [40]:
#Defining an instance of the class

p=ClassName(5,10)

p.property1 = 4 #To access the variable "property1" of the object p and change it from 5 to 4

result=p.funct1(20,30)   # To call the function funct1 of the class object p, with the parameters a=20 and b=30, and stores the return value in the variable result

Operation Complete


## Enumerate()

Enumerate() is a built-in function in python, which allows us to keep a count of the iterable. It returns an object of type enumerate, which incorporates both the count as well as values of the iterable

__Syntax__

enumerate(iterable,start=initial_count)  # iterable is any object which supports iteration 

_initial_count is the starting index of the counter
The default value of initial_count is 0_

In [41]:
# An example of how to implement enumerate() and convert a list to enumerate object

l1 = ["eat","sleep","repeat"] 

# creating enumerate objects 
obj1 = enumerate(l1,start=0) 

for i,val in obj1:
    print(i)
    print(val)

0
eat
1
sleep
2
repeat
